name: Deploy Docker Container

on:
  push:
    branches:
      - deploy-test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SHA256:xhQmOhgCk54HhJaiD4fKBEhf9wpaC6Th8Zm2bR9gjH8}}

    - name: Deploy to server
      run: |
        ssh -o StrictHostKeyChecking=no root@192.168.1.20 << EOF
          docker pull tioallen/regrill-webapp:latest
          docker stop regrill-webapp || true
          docker rm regrill-webapp || true
          docker run -d -p 8080:80 --name regrill-webapp tioallen/regrill-webapp:latest
        EOF
